apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paul-app
  name: paul-app
spec:
  selector:
    matchLabels:
      app: paul-app
  template:
    metadata:
      labels:
        app: paul-app
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged
        name: paul-app
        ports:
        - containerPort: 8080
