apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  destination:
    name: ''
    namespace: homelab
    server: 'https://kubernetes.default.svc'
  source:
    path: demo/overlays/dev
    repoURL: 'https://github.com/paul6668/test.git'
    targetRevision: HEAD
    directory:
      recurse: false
  project: homelab
