apiVersion: batch/v1
kind: Job
metadata:
  name: presync-test
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  selector: {}
  template:
    metadata:
      name: presync-test
    spec:
      containers:
        - name: presync-test
          image: nginxinc/nginx-unprivileged
          command:
            - "curl"
            - "http://www.google.com"
      restartPolicy: Never
